apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-sample-python-app
  namespace: argocd
spec:
  description: Argo CD project for the sample Python application
  sourceRepos:
    - https://github.com/pandeyaws/sample-python-app.git
    - https://github.com/pandeyaws/sample-python-app-argocd.git
  destinations:
    - namespace: dev-sample-python-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: apps-sample-python-app
  namespace: argocd   
spec:
  project: apps-sample-python-app 
  source:
    repoURL: https://github.com/pandeyaws/sample-python-app-argocd.git
    targetRevision: master
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-sample-python-app  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true
      - serverside-apply=true  
