apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/pandeyaws/scf-k8s-argocd.git
    targetRevision: main
    path: applications/platform

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true